### ISSUE TITLE
The seed folder and or content seems to be missing...

### ISSUE THREAD

**Issue by matthewkyleherren** [payloadcms/custom-website-series#5]
I really think that this site would give so much opportunity to learn from, and so much more so if it came with its seed content. Would it be possible to put that back in?

**Comment by denolfe** [comment]
Hey @mrsungura , the seeding still remains in the upstream repo [here](https://github.com/payloadcms/nextjs-custom-server). There is also some more complex seeding done in our [public-demo](https://github.com/payloadcms/public-demo/blob/master/src/cron/reset.ts) that may be worth looking at as well.
